development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgres
  url: postgres://jvauwluqkrheje:2rTsG0oRLL0802mQ32fon4_GJ_@ec2-54-83-44-229.compute-1.amazonaws.com:5432/db25or2dpkvfc
